# Public gist backing `just publish-report`. Override on the command line to
# push elsewhere: `just report_gist=<id> publish-report`.
report_gist := "3879f386243f99dab4b4c9071e09c0d5"

default: t

t *args:
    cargo build-sbf
    cargo test --workspace --features amm/test-helpers {{args}}

tt *args:
    cargo build-sbf
    cargo test --workspace --features amm/test-helpers {{args}} -- --nocapture --test-threads=1

# classroom artifact for docs/security/exercises/001-what-is-going-on.md.
#
# Run the lock/unlock PoC with full structured-log output.
poc:
    cargo build-sbf
    cargo test --workspace --features amm/test-helpers --test test_lock_unlock_attack -- --nocapture --test-threads=1


# Each test emits target/md-reports/<slug>.md via the `Report` recorder; we wipe
# that dir first (so a renamed test can't leave a stale section behind), then
# concatenate in sorted order behind a generated-file banner, separated by
# rules. Output is byte-stable across runs (seeded keypairs), so it diffs clean.
#
# Assemble per-scenario reports into one doc, docs/testing/test-report.md.
test-md:
    #!/usr/bin/env bash
    set -euo pipefail
    cargo build-sbf
    rm -rf target/md-reports
    cargo test --workspace --features amm/test-helpers
    out=docs/testing/test-report.md
    mkdir -p docs/testing
    {
        echo '<!-- GENERATED by `just test-md`; do not edit by hand. -->'
        echo '# AMM Test Report'
        echo
        echo 'One section per integration-test scenario, emitted by the `Report`'
        echo 'recorder and concatenated in sorted order. Regenerate with `just test-md`.'
        echo
        for f in $(ls target/md-reports/*.md | LC_ALL=C sort); do
            cat "$f"
            printf '\n---\n\n'
        done
    } > "$out"
    echo "wrote $out ($(ls target/md-reports/*.md | wc -l) scenarios)"

# Depends on test-md so the gist can never be staler than the code. NOTE: pushes
# to a PUBLIC gist; the report embeds the deterministic (throwaway, never-funded)
# test pubkeys, which is harmless but is a deliberate disclosure.
#
# Regenerate the test report and publish it to the public gist ($report_gist).
publish-report: test-md
    #!/usr/bin/env bash
    set -euo pipefail
    gh gist edit {{report_gist}} --filename test-report.md docs/testing/test-report.md
    echo "published docs/testing/test-report.md -> https://gist.github.com/{{report_gist}}"


# Build and open documentation for amm and amm-math crates (no external deps)
doc:
    cargo doc --open --no-deps -p amm -p amm-math
